M48
; DRILL file {KiCad 8.0.1-8.0.1-1~ubuntu22.04.1} date 2024-04-10T22:34:26-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-10T22:34:26-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1-8.0.1-1~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.300
%
G90
G05
T1
X4.5Y48.86
X4.5Y3.14
X40.5Y48.86
X40.5Y3.14
M30
